language: generic

services:
  - docker

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: bash ./ci/test
    - stage: "Build"
      name: "Build and Push Docker Image"
      script: bash ./ci/docker_push
    - stage: "Deploy"
      if: branch = master
      name: "Deploy using Terraform"
      script: bash ./ci/deploy
