sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t c2/hello-world .

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: docker run c2/hello-world python manage.py test
    - stage: "Build"
      name: "Build and Push Docker Image"
      script: bash ./ci/docker_push


# before_install:
#   - docker build -t c2/hello-world .
#
# script:
#   - ./ci/test.sh
#   - docker run c2/hello-world python manage.py test
