#!/bin/bash

set -e

docker run -it \
  -v $(pwd)/tf/:/app/ \
  -w /app/ \
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  hashicorp/terraform:light init

docker run -it \
  -v $(pwd)/tf/:/app/ \
  -w /app/ \
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  hashicorp/terraform:light apply --auto-approve
