#!/bin/bash

set -e

TERRAFORM_IMAGE=hashicorp/terraform:0.11.8

docker run -it \
  -v $(pwd)/tf/:/app/ \
  -w /app/ \
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  $TERRAFORM_IMAGE init

docker run -it \
  -v $(pwd)/tf/:/app/ \
  -w /app/ \
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  $TERRAFORM_IMAGE apply --auto-approve
