#!/bin/bash

TERRAFORM_IMAGE=hashicorp/terraform:0.11.8

set -e

docker run -it \
  -v $(pwd)/tf/:/app/ \
  -w /app/ \
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  -e "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" \
  $TERRAFORM_IMAGE init

docker run -it \
  -v $(pwd)/tf/:/app/ \
  -w /app/ \
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  -e "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" \
  $TERRAFORM_IMAGE destroy
